version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=mydbuser
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mydbuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
