version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    environment:
      - PORT=3000
  mongo-db:
    image: mongo
    volumes:
      - mongo_db:/data/db
  redis:
    image: redis
volumes:
  mongo_db:
